### ISSUE TITLE
Feature Request: Save settings in the boot-up Configuration dialog box.

### ISSUE THREAD

**Issue by ghost** [openMSX/catapult#2]
![image](https://user-images.githubusercontent.com/6374154/100002836-fc2c8180-2d79-11eb-8389-3d4c37c0a8a6.png)

It should be saving the settings here, but for some reason it isn't. Particularly the check box option.

**Comment by MBilderbeek** [comment]
These settings are saved, as you probably saw in the registry. I think this is related to the path problem with the $, do you agree? If yes, then this issue can be closed.

**Comment by ghost** [comment]
It appears to be directly related, yes. The settings will not save if there's an issue with the path.

**Comment by MBilderbeek** [comment]
As this feature is already implemented, but seems to malfunction as per #1, I'm closing this ticket.
