### ISSUE TITLE
Catapult version & date mismatching with current openMSX RC versions

### ISSUE THREAD

**Issue by Dalekamistoso** [openMSX/catapult#3]
Catapult version and years does not correspond with openmsx release version (tested on RC1)

(I add this issue because openMSX is already in release candidate cycle, take it only as a reminder)

![image](https://user-images.githubusercontent.com/67012746/170722192-a63b1904-f17b-4bdc-84b4-532570420ef0.png)

Thanks in advance :)

**Comment by MBilderbeek** [comment]
That's just an artifact on how @Vampier is building the combination. He doesn't always pull the latest Catapult code for the produced installer.
Not something in our code repo, so closing this. Thanks for the reminder though.

**Comment by Vampier** [comment]
Allang opgelost - “it’s take it or leave it” vanaf dit moment. Ik heb geen zin in ‘demands’ van iets wat ik gratis doe. 

Sorry dat ik kortaf ben
